version: 2.1

defaults: &environment
  docker:
    - image: python:3.7-alpine3.11

jobs:
  build_environment:
    <<: *environment
    steps:
      - checkout
      - run: aws cloudformation deploy --template-file template.yml --stack-name my-stack
  deploy_environment:
    <<: *environment
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["72:74:85:21:95:96:db:d6:2c:ab:a1:b2:72:16:88:0a"]
      - run:
          name: Install Dependencies
          command: |
            apk add --update ansible


workflows:
  cd:
    jobs:
      #- build_environment
      - deploy_environment