version: 2.1

defaults: &environment
  docker:
    - image: amazon/aws-cli

jobs:
  build_environment:
    <<: *environment
    steps:
      - checkout
      - run: aws cloudformation create-stack --stack-name cd --template-body file://template.yml  --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=eu-central-1

workflows:
  cd:
    jobs:
      - build_environment